version: '3.8'
services:
  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - modelersrift-db:/var/lib/postgresql/data
volumes:
  modelersrift-db:
