export const STAT_OPTIONS = [
  { label: 'Attack Damage', value: 'attackdamage' },
  { label: 'Armor', value: 'armor' },
  { label: 'Magic Resist', value: 'spellblock' },
  { label: 'Health', value: 'hp' },
  { label: 'Mana', value: 'mp' },
  { label: 'Health Regen', value: 'hpregen' },
  { label: 'Mana Regen', value: 'mpregen' },
  { label: 'Crit', value: 'crit' },
  { label: 'Attack Speed', value: 'attackspeed' },
]

export const STAT_SEMANTIC_TEMPLATES: Record<string, string> = {
  '<physicalDamage>': 'Physical Damage',
  '<magicDamage>': 'Magic Damage',
  '<status>': 'Status',
  '<recast>': 'Recast',
  '<lifeSteal>': 'Life Steal',
  '<spellPassive>': 'Passive',
  '<spellActive>': 'Active',
  '<scaleAD>': 'Scale AD',
  '<healing>': 'Healing',
  '<speed>': 'Speed',
  '<keywordStealth>': 'Stealth',
}

export enum AssetType {
  ANIMATION = 'animation',
  SFX = 'sfx',
  VO = 'vo',
}

export const HTTP_SAFE_CHAMPION_NAMES = [
  'Aatrox',
  'Ahri',
  'Akali',
  'Alistar',
  'Amumu',
  'Anivia',
  'Annie',
  'Ashe',
  'Azir',
  'Belveth',
  'Blitzcrank',
  'Brand',
  'Braum',
  'Caitlyn',
  'Cassiopeia',
  'Chogath',
  'Corki',
  'Darius',
  'Diana',
  'DrMundo',
  'Draven',
  'Elise',
  'Evelynn',
  'Ezreal',
  'Fiddlesticks',
  'Fiora',
  'Fizz',
  'Galio',
  'Gangplank',
  'Garen',
  'Gnar',
  'Gragas',
  'Graves',
  'Hecarim',
  'Heimerdinger',
  'Irelia',
  'Janna',
  'JarvanIV',
  'Jax',
  'Jayce',
  'Jinx',
  'Kalista',
  'Karma',
  'Karthus',
  'Kassadin',
  'Katarina',
  'Kayle',
  'Kennen',
  'Khazix',
  'KogMaw',
  'Leblanc',
  'LeeSin',
  'Leona',
  'Lissandra',
  'Lucian',
  'Lulu',
  'Lux',
  'Malphite',
  'Malzahar',
  'Maokai',
  'MasterYi',
  'MissFortune',
  'Mordekaiser',
  'Morgana',
  'Nami',
  'Nasus',
  'Nautilus',
  'Nidalee',
  'Nilah',
  'Nocturne',
  'Nunu',
  'Olaf',
  'Orianna',
  'Ornn',
  'Pantheon',
  'Poppy',
  'Quinn',
  'Rammus',
  'RekSai',
  'Renata',
  'Renekton',
  'Rengar',
  'Riven',
  'Rumble',
  'Ryze',
  'Sejuani',
  'Shaco',
  'Shen',
  'Shyvana',
  'Singed',
  'Sion',
  'Sivir',
  'Skarner',
  'Sona',
  'Soraka',
  'Swain',
  'Syndra',
  'Talon',
  'Taric',
  'Teemo',
  'Thresh',
  'Tristana',
  'Trundle',
  'Tryndamere',
  'TwistedFate',
  'Twitch',
  'Udyr',
  'Urgot',
  'Varus',
  'Vayne',
  'Veigar',
  'Velkoz',
  'Vi',
  'Viktor',
  'Vladimir',
  'Volibear',
  'Warwick',
  'Wukong',
  'Xerath',
  'XinZhao',
  'Yasuo',
  'Yorick',
  'Zac',
  'Zed',
  'Zeri',
  'Ziggs',
  'Zilean',
  'Zyra',
  'Bard',
  'Ekko',
  'TahmKench',
  'Kindred',
  'Illaoi',
  'Jhin',
  'AurelionSol',
  'Taliyah',
  'Kled',
  'Ivern',
  'Camille',
  'Rakan',
  'Xayah',
  'Kayn',
  'Rrnn',
  'Zoe',
  'Kaisa',
  'Pyke',
  'Neeko',
  'Sylas',
  'Yuumi',
  'Qiyana',
  'Senna',
  'Aphelios',
  'Sett',
  'Lillia',
  'Yone',
  'Samira',
  'Seraphine',
  'Rell',
  'Viego',
  'Gwen',
  'Akshan',
  'Vex',
]
