/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
https://gltf.pmnd.rs/
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
// @ts-ignore
import aatrox from '../assets/aatrox.glb'

export default function Model(props) {
  const group = useRef()
  // @ts-ignore
  const { nodes, materials, animations } = useGLTF(aatrox)
  const { actions } = useAnimations(animations, group)

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime()
    // @ts-ignore
    group.current.rotation.y = a * 0.3
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
        <primitive object={nodes.Root} />
        <primitive object={nodes.Weapon_World} />
        <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
        <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
        <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
        <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
        <primitive object={nodes.RunPython} />
        <primitive object={nodes.Buffbone_Cstm_Healthbar} />
        <primitive object={nodes.Body_World} />
        <skinnedMesh
          geometry={nodes.Mesh_0001_1.geometry}
          material={materials['Wings.001']}
          skeleton={nodes.Mesh_0001_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh_0001_2.geometry}
          material={materials['Body.001']}
          skeleton={nodes.Mesh_0001_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh_0001_3.geometry}
          material={materials['Sword.001']}
          skeleton={nodes.Mesh_0001_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh_0001_4.geometry}
          material={materials['Shoulder.001']}
          skeleton={nodes.Mesh_0001_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Mesh_0001_5.geometry}
          material={materials['Banner.001']}
          skeleton={nodes.Mesh_0001_5.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload(aatrox)
