/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
// @ts-ignore
import poppy from '../assets/poppy.glb'

export default function Model(props) {
  const group = useRef()
  // @ts-ignore
  const { nodes, materials, animations } = useGLTF(poppy)
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]}>
        <primitive object={nodes.Root} />
        <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
        <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
        <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
        <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
        <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
        <primitive object={nodes.C_Buffbone_Cstm_Healthbar_Loc} />
        <primitive object={nodes.Snap_Weapon2World} />
        <skinnedMesh
          geometry={nodes.Mesh_0.geometry}
          material={materials.Poppy_Mat}
          skeleton={nodes.Mesh_0.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload(poppy)
